// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import Dropdown from "stimulus-dropdown";
import { Modal } from "tailwindcss-stimulus-components"
import { Alert } from "tailwindcss-stimulus-components"
import HelloController from "./hello_controller";
import VisibilityController from "./visibility_controller"
import CartController from "./cart_controller"


application.register('modal', Modal)
application.register('alert', Alert)
application.register("dropdown", Dropdown);
application.register("hello", HelloController);
application.register("visibility", VisibilityController)
application.register('cart', CartController)
