// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import { Alert } from "tailwindcss-stimulus-components"
import VisibilityController from "./visibility_controller"



application.register('alert', Alert)
application.register("visibility", VisibilityController)
